name: Build Mac Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies
        run: |
          brew install portaudio
          brew install ffmpeg
          FFMPEG_PATH=$(which ffmpeg)
          echo "Found ffmpeg at: $FFMPEG_PATH"
          echo "FFMPEG_PATH=$FFMPEG_PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install openai-whisper
          pip install -r requirements.txt

      - name: Build macOS Executable
        run: |
          pyinstaller --onefile --name clip_that_script-x86_64-apple-darwin \
          --add-data "${{ env.FFMPEG_PATH }}:bin" \
          --add-data "${{ env.pythonLocation }}/lib/python${{ matrix.python-version }}/site-packages/whisper:whisper/" \
          --recursive-copy-metadata "openai-whisper" \
          clip_that_script.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clip_that_script-macos
          path: dist/*
          retention-days: 90
